movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name', 'desc', 'year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm


# Create your views here.
def update(request, id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form':form, 'movie':movie})


def index(request):
    movie=Movie.objects.all
    context={
        'movie_list':movie
    }
    return render(request, 'index.html', context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/movieapp/templates/add.html
<title>Add Movie</title>
{% extends 'base.html' %}
{% block body %}

<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <h3>Add Movie</h3> <br><br>
    <input type="text" name="name" placeholder="Enter Movie Name"><br><br>
    <input type="text" name="desc" placeholder="Enter Movie Description"><br><br>
    <input type="text" name="year" placeholder="Enter Movie Year"><br><br>
    <input type="file" name="img"><br><br><br>
    <input type="submit">

</form>

{% endblock %}

movieproject/movieapp/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- As a link -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Movies Online </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/movieapp/templates/delete.html
<title>Delete Movie </title>
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <br>
    <br>
    Are you sure want to delete?
    <input type="submit" value="Yes">

</form>
{% endblock %}

movieproject/movieapp/templates/detail.html
<title>Details </title>
{% extends 'base.html' %}
{% block body %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h5>{{movie.name}}</h5><br><br>
            <img src="{{movie.img.url}}" width="300" height="200">
        </div>
            <div class="col-md-6">

                <b>{{movie.desc}}<br><br>
                    {{movie.year}}</b><br><br>
                <a class="btn btn-dark" href="{% url 'movieapp:update' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
            </div>
       </div>
</div>
{% endblock %}

movieproject/movieapp/templates/edit.html
<title>Edit Movie </title>
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

movieproject/movieapp/templates/index.html
<title>Home</title>
{% extends 'base.html' %}
{% block body %}\
<br>
<div class="container">

    <div class="row">
        <br><br><br>
        {% for i in movie_list %}
        <div class="col-md-4">
            &nbsp
            <div class="card" style="width: 22rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="286" height="180">

                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                    </div>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

<br>
<p align="center">
    <a href="{% url 'movieapp:add_movie' %}" class="btn btn-dark" style="text-align:center";>Add Movie</a>
</p>
{% endblock %}